version: '3.5'
services:
  api:
    container_name: echo_api
    build:
      context: ../
      dockerfile: Echo.WebApi/Dockerfile
    networks: 
      - public_network
    ports:
      - 81:80
      - 444:443
    volumes: 
      - D:\Git\Echo.WebApi\Echo.WebApi\tools\:/config
      
  proxy: 
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - D:\Git\Echo.WebApi\Echo.WebApi\tools\nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public_network
    depends_on: 
      - api

networks:
  public_network:
    driver: bridge
    name: public_network